# YAML Configuration for XML Content Replacement
# This configuration file defines regex patterns and replacement rules for updating metadata files.
# It is designed to work with a Python script that automates the search and replace process
# across different environments (POOL, DEV, UAT, STG, PROD), allowing for environment-specific
# text replacements within specified metadata XML files.

# 'regex_lib' section defines common regex patterns for identifying specific XML elements and attributes.
# 'rules' section specifies the replacement operations, mapping each rule to a list of target files,
# the regex pattern to use (referenced from 'regex_lib'), and the replacement text for each environment.

regex_lib:
  site_admin: '<siteAdmin>\s*([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})\s*<\/siteAdmin>'
  email_sender_address: '<emailSenderAddress>([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})<\/emailSenderAddress>'
rules:
  replace_site_admin:
    files:
      - 'main/default/sites/accesslist.site-meta.xml'
    regex_name: 'site_admin'
    replace_with: 
      POOL: '<siteAdmin>testuser@salesforce.com.pool</siteAdmin>' 
      DEV: '<siteAdmin>testuser@salesforce.com.dev</siteAdmin>'
      UAT: '<siteAdmin>testuser@salesforce.com.uat</siteAdmin>'
      STG: '<siteAdmin>testuser@salesforce.com.stg</siteAdmin>'
      PROD: '<siteAdmin>testuser@salesforce.com.dev</siteAdmin>'
  replace_email_sender_address:
    files:
      - 'main/default/networks/accesslist.network-meta.xml'
    regex_name: 'email_sender_address'
    replace_with: 
      POOL: '<emailSenderAddress>testuser@salesforce.com</emailSenderAddress>'
      DEV: '<emailSenderAddress>testuser@salesforce.com</emailSenderAddress>'
      UAT: '<emailSenderAddress>testuser@salesforce.com</emailSenderAddress>'
      STG: '<emailSenderAddress>testuser@salesforce.com</emailSenderAddress>'
      PROD: '<emailSenderAddress>testuser@salesforce.com</emailSenderAddress>'
