# DX@Scale CI/CD Template for GitHub
#----------------------------------------------------------------------------------------------------
# Follows reference pipeline available at docs.dxatscale.io
# 
#-----------------------------------------------------------------------------------------------------
# To know more about dxatscale, visit https://docs.dxatscale.io
# To know more on sfpowerscripts, visit- https://sfpowerscripts.dxatscale.io/
# To know more on sfpowerkit, visit- https://github.com/Accenture/sfpowerkit

# This pipeline quickbuilds, deploy to DEV, builds and publishes packages to artifact repository

name: 'CI Pipeline - Auto Triggered'


on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "src*/**"
      - "sfdx-project*"


  workflow_dispatch:



#Set the environment variables for tracking metrics
env:
  ENABLE_SF_LOGGING: ${{vars.ENABLE_SF_LOGGING}}
  #SFPOWERSCRIPTS_NEWRELIC: 'true'
  #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}'
  #SFPOWERSCRIPTS_DATADOG: 'true'
  #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'



jobs:
  quickbuild:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    name: 'Quickbuild packages'
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    outputs:
      artifacts_uploaded: ${{ steps.set_upload_flag.outputs.artifacts_uploaded }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Authenticate Dev Hub'
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url  -f authfile -a devhub

      - name: Configure SF CLI Logging
        if: env.ENABLE_SF_LOGGING == 'true'
        run: | 
          echo "SF_LOG_LEVEL=debug" >> $GITHUB_ENV
  
      - name: 'Create packages'
        id: sfpowerscripts-build
        run: |
          sfp orchestrator:quickbuild -v devhub --diffcheck --buildnumber ${GITHUB_RUN_ID} --branch ${GITHUB_REF#refs/heads/}

      - name: Prepare Artifact Directory
        if: env.ENABLE_SF_LOGGING == 'true'
        run: |
          mkdir -p sf-logs
          cp $HOME/.sf/sf* sf-logs/
        shell: bash
    
      - name: Upload SF CLI Log as Artifact
        if:  env.ENABLE_SF_LOGGING == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: sf-logs-quickbuild
          path: sf-logs/

      - name: Check for artifacts to upload
        id: artifact_check
        run: |
          if [ "$(ls -A artifacts/)" ]; then
            echo "Artifacts exist for upload."
            echo "artifacts_exist=true" >> $GITHUB_ENV
          else
            echo "No artifacts exist for upload."
            echo "artifacts_exist=false" >> $GITHUB_ENV
          fi

      # Publish artifacts
      - uses: actions/upload-artifact@v2  
        if: env.artifacts_exist == 'true'
        with:
          name: quickbuild-artifacts
          path: artifacts

      - name: Set upload flag
        id: set_upload_flag
        run: echo "artifacts_uploaded=${{ env.artifacts_exist }}" >> $GITHUB_OUTPUT

  deploy:
    name: 'Deploy to Dev'
    runs-on: ubuntu-latest
    env:
      TARGET_ENVIRONMENT: 'DEV'
    container: ghcr.io/dxatscale/sfpowerscripts
    needs: quickbuild
    concurrency: dev
    if: ${{ needs.quickbuild.outputs.artifacts_uploaded == 'true' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install PyYAML
        run: python -m pip install pyyaml 

      - name: "Download Quickbuild Artifacts"
        id: download-artifacts  
        uses: actions/download-artifact@v2
        with:
          name: quickbuild-artifacts
          path: artifacts 

      - name:  'Authenticate Dev Hub'
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url  -f authfile -a devhub

      - name: Authenticate to DEV sandbox
        run: |
          echo "${{ secrets.DEV_SFDX_AUTH_URL }}" > ./dev_authfile
          sf org login sfdx-url  -f ./dev_authfile -a dev

      - name: Configure SF CLI Logging
        if: ${{ env.ENABLE_SF_LOGGING == 'true' }}
        run: | 
          echo "SF_LOG_LEVEL=debug" >> $GITHUB_ENV

      - name: 'Deploy to DEV'
        run: |
          sfp dependency:install -u dev -v devhub
          sfp orchestrator:deploy -u dev  --skipifalreadyinstalled -g "::group::,::endgroup::" 

      - name: Prepare Artifact Directory
        if: ${{ env.ENABLE_SF_LOGGING == 'true' }}
        run: |
          mkdir -p sf-logs
          cp $HOME/.sf/sf* sf-logs/
        shell: bash
      
      - name: Upload SF CLI Log as Artifact
        if: ${{ env.ENABLE_SF_LOGGING == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: sf-logs-deploy
          path: sf-logs/

  buildAndPublish:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    needs: [deploy, quickbuild]
    concurrency: build 
    if: ${{ needs.quickbuild.outputs.artifacts_uploaded == 'true' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Authenticate Dev Hub'
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url  -f authfile -a devhub

      - name: Configure SF CLI Logging
        if: env.ENABLE_SF_LOGGING == 'true'
        run: | 
          echo "SF_LOG_LEVEL=debug" >> $GITHUB_ENV

      - name: 'Create packages'
        id: sfpowerscripts-build
        run: |
          sfp orchestrator:build -v devhub --diffcheck --branch ${GITHUB_REF#refs/heads/} --buildnumber ${GITHUB_RUN_ID}

      - name: Prepare Artifact Directory
        if: env.ENABLE_SF_LOGGING == 'true'
        run: |
          mkdir -p sf-logs
          cp $HOME/.sf/sf* sf-logs/
        shell: bash
  
      - name: Upload SF CLI Log as Artifact
        if:  env.ENABLE_SF_LOGGING == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: sf-logs-buildAndPublish
          path: sf-logs/

      # Publish artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: artifacts

      # Authenticate to npm
      - uses: actions/setup-node@v3
        with:
         registry-url: 'https://npm.pkg.github.com'

      - name: Publish
        run: |
          sfp orchestrator:publish -d artifacts --npm --scope @${{ github.repository_owner }}  --gittag --pushgittag
        env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
