name: Release Definition Prep

on:
  push:
    branches:
      - main
    paths:
      - 'release-definitions/release-vars-file.json'

jobs:
  RELEASE_DEFN_PREP:
    name: 'Release Definition Prep'
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    if: contains(github.ref,'refs/heads/main')
    
    steps:
      - uses: actions/checkout@v2
      - name: Generate Release Definition
        run: bash ./scripts/releaseDefinition.sh
