# Deploy to Production Workflow
#
# This workflow handles the deployment of the release to the production environment.
# It is manually triggered and allows the user to specify the release definition file to be used.
# The specified file should be a previously generated and manually reviewed release definition file
# located in the 'release-definitions' directory. This approach ensures that deployments to 
# production are conducted with caution and after necessary approvals.
#
# Workflow Triggers:
# - Manually triggered via GitHub's workflow_dispatch event.
# - Allows input for specifying the release definition file name.
#
# Workflow Steps:
# 1. Checkout the repository.
# 2. Deploy the release using the specified release definition file.
#

name: Test Production Release

on: pull_request

jobs:
  PROD:
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    environment:
      name: PROD

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            src:
              - 'release-definitions/release-def.yml'
    
      # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.src == 'true'

      - name: Authenticate to PROD
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url  -f ./authfile -a prod

      # Authenticate to npm
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'

      # Release to environment  
      - name: Release to PROD
        run: sfp orchestrator:release -u prod -p release-definitions/plan_release_def.yml --npm --scope ${{ github.repository_owner }} --generatechangelog --branchname changelog -g "::group::,::endgroup::"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
