# Generate Release Definition Workflow
#
# This workflow is responsible for automatically generating the release definition file.
# It is triggered when changes to 'release-vars-file.json' are merged into the main branch.
# The workflow runs a script that generates a release definition file based on the 
# parameters specified in 'release-vars-file.json'. The generated file is committed to the 
# repository, allowing for manual review and modifications before the deployment process.
#
# Workflow Triggers:
# - Pull request merge into the main branch, specifically when changes are made to 'release-vars-file.json'.
#
# Workflow Steps:
# 1. Checkout the repository.
# 2. Run the script to generate the release definition file
#

name: Release Definition Prep

on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Release Name'
        required: false
        default: 'release_def'
      directory:
        description: 'Directory to which release definition file is written'
        required: false
        default: 'release-definitions'
      configFile:
        description: 'Path to the config file'
        required: false
        default: 'release-definitions/release-template.yml'

jobs:
  generate-release-definition:
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Generate Release Definition
        run: bash ./scripts/releaseDefinition.sh "${{ github.event.inputs.releaseName }}" "${{ github.event.inputs.directory }}" "${{ github.event.inputs.configFile }}"