# ----------------------------------------------------------------------------
#
# Perform static static analysis of Apex code using Salesforce Code Analyzer
#
# ----------------------------------------------------------------------------

name: Salesforce Code Analyzer Workflow

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, labeled]
    branches:
      - main

  workflow_dispatch:

jobs:
  salesforce-code-analyzer-workflow:
    name: 'Code Analyzer Scan'
    if: >
      (github.event_name == 'pull_request' &&
      (github.event.action == 'opened' ||
      (github.event.action == 'labeled' && github.event.label.name == 'ready-for-final-test'))) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'workflow_dispatch')
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v0.1.16
        with:
          #pmdconfig: masterRuleset.xml
          severity-threshold: 4
          strictly-enforced-rules: '[{ "engine": "pmd", "category": "Error Prone", "rule": "AvoidHardcodingId" }]'
          report-mode: comments
          delete-resolved-comments: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
