# DX@Scale CI/CD Template for GitHub
#----------------------------------------------------------------------------------------------------
# Follows reference pipeline available at docs.dxatscale.io
# 
#-----------------------------------------------------------------------------------------------------
# To know more about dxatscale, visit https://docs.dxatscale.io
# To know more on sfpowerscripts, visit- https://sfpowerscripts.dxatscale.io/
# To know more on sfpowerkit, visit- https://github.com/Accenture/sfpowerkit


# This pipeline is used to validate an incoming change using a dev environment fetched from the CI pool

name: 'PR Validation on Initial and Final Approval - Auto Triggered'

on:
  pull_request:
    types: [opened, labeled]
    branches:
      - main
    paths:
      - "src*/**"
      - "sfdx-project*"


  workflow_dispatch:


jobs:
  validate:
    name: 'Validate Changed Packages'
    if: >
      github.event_name == 'pull_request' &&
      (github.event.action == 'opened' ||
       github.event.action == 'labeled' && github.event.label.name == 'ready-for-final-test')
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Authenticate Dev Hub'
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url  -f authfile -a devhub

      - name: 'Validate source and trigger test'
        run: |
          sfp orchestrator:validate -p ci -v devhub -x > release.log
          cat release.log

      - name: 'Check for Deleting scratch org'
        run: |
          if grep -q "Deleting scratch org" release.log; then
            echo "Scratch org deleted. Preparing new one."
            echo "SCRATCH_ORG_DELETED=true" >> $GITHUB_ENV
          else
            echo "No scratch org deletion detected."
            echo "SCRATCH_ORG_DELETED=false" >> $GITHUB_ENV
          fi

      - name: 'Trigger Separate Workflow for Scratch Org Preparation'
        if: env.SCRATCH_ORG_DELETED == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{"event_type": "prepare-scratch-org"}'
