# ----------------------------------------------------------------------------
#
# Perform static static analysis of Apex code using Salesforce Code Analyzer
#
# ----------------------------------------------------------------------------

name: Salesforce Code Analyzer Workflow

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, labeled]
    branches:
      - main

  workflow_dispatch:

jobs:
  salesforce-code-analyzer-workflow:
    name: 'Code Analyzer Scan'
    if: >
      (github.event_name == 'pull_request' &&
      (github.event.action == 'opened' ||
      (github.event.action == 'labeled' && github.event.label.name == 'ready-for-final-test'))) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'workflow_dispatch')
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --pmdconfig ${GITHUB_WORKSPACE}/rulesets/masterRuleset.xml --target . --outfile results.html
          results-artifact-name: salesforce-code-analyzer-results

      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
